### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by adrael** [Eptwalabha/termites-projet-ia#1]
Pour mener à bien le projet en parallèle, il faudrait établir une ToDo list agile style, chacun ayant ces tâches.

Qu'en penses tu ?

**Comment by Eptwalabha** [comment]
Ouaich, pas bête.

Je t'appelle ce soir sur Skype ou Steam car là je n'ai pas le temps en
entreprise. Mais j'aime bien l'idée.
sinon t'en penses quoi de la strat? y'avais que nous deux sur ce projet?
